# Data Cleaning

En este proceso llevamos acabo una limpieza de las tablas: 
1. **Productos**
2. **Tiendas**
3. **Ventas**
En todas aplicaremos una verificación de valores nulos, duplicadios, missings y formato de los datos. Este desarrollo nos permitirá  consolidar los datos en una única tabla final:
4. **DataFrame-Final** 

## Librerías necesarias

In [1]:
import pandas as pd
import unicodedata

## Datasets

In [2]:
# Lectura de los archivos csv
productos = pd.read_csv('..\\data\\productos.csv')
tiendas = pd.read_csv('..\\data\\tiendas.csv')
ventas = pd.read_csv('..\\data\\ventas.csv')

## 1. Productos

In [3]:
# Dataframe inicial de productos
productos.head()

product_id           product_name           category  price  cost  \
0         101       Cafetera Premium  Electrodomesticos     90  60.0   
1         102        Cafetera Básica  Electrodomesticos     60  40.0   
2         103  Tostadora 2 rebanadas  Electrodomesticos     30  20.0   
3         104  Tostadora 4 rebanadas  Electrodomesticos     50  30.0   
4         105      Batidora Compacta  Electrodomesticos     80   NaN   

  launch_date  status  
0  2023-01-01  active  
1  2023-01-15  active  
2  2022-11-01  active  
3  2022-12-01  paused  
4  2023-02-01  active

In [4]:
# Verificamos si hay valores nulos
productos.isnull().sum()

product_id      0
product_name    0
category        0
price           0
cost            1
launch_date     0
status          0
dtype: int64

In [5]:
# Suma de las filas con valores nulos
productos.duplicated().sum()

1

In [6]:
# Reemplazamos los valores nulos con el 30% del prcio ya que por la tendencia de los datos se puede inferir que el costo es el 30% menos del precio
productos['cost'].fillna(productos['price'] - productos['price'] * 0.3, inplace=True)

In [7]:
# Eliminamos los productos duplicados por el product_id
productos.drop_duplicates(subset='product_id', inplace=True)
productos.head()

product_id           product_name           category  price  cost  \
0         101       Cafetera Premium  Electrodomesticos     90  60.0   
1         102        Cafetera Básica  Electrodomesticos     60  40.0   
2         103  Tostadora 2 rebanadas  Electrodomesticos     30  20.0   
3         104  Tostadora 4 rebanadas  Electrodomesticos     50  30.0   
4         105      Batidora Compacta  Electrodomesticos     80  56.0   

  launch_date  status  
0  2023-01-01  active  
1  2023-01-15  active  
2  2022-11-01  active  
3  2022-12-01  paused  
4  2023-02-01  active

Formato de los datos

In [8]:
# Conocer el tipo de datos de los productos
productos.dtypes

product_id        int64
product_name     object
category         object
price             int64
cost            float64
launch_date      object
status           object
dtype: object

In [9]:
# Transformamos los datos a su tipo correspondiente: price a float, launch_date a datetime
productos["price"] = productos["price"].astype(float)
productos['launch_date'] = pd.to_datetime(productos['launch_date'])


In [10]:
# Verificamos como queda la tabla de productos
productos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20 entries, 0 to 20
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   product_id    20 non-null     int64         
 1   product_name  20 non-null     object        
 2   category      20 non-null     object        
 3   price         20 non-null     float64       
 4   cost          20 non-null     float64       
 5   launch_date   20 non-null     datetime64[ns]
 6   status        20 non-null     object        
dtypes: datetime64[ns](1), float64(2), int64(1), object(3)
memory usage: 1.2+ KB


In [11]:
# Dataframe final de productos
productos.head()

product_id           product_name           category  price  cost  \
0         101       Cafetera Premium  Electrodomesticos   90.0  60.0   
1         102        Cafetera Básica  Electrodomesticos   60.0  40.0   
2         103  Tostadora 2 rebanadas  Electrodomesticos   30.0  20.0   
3         104  Tostadora 4 rebanadas  Electrodomesticos   50.0  30.0   
4         105      Batidora Compacta  Electrodomesticos   80.0  56.0   

  launch_date  status  
0  2023-01-01  active  
1  2023-01-15  active  
2  2022-11-01  active  
3  2022-12-01  paused  
4  2023-02-01  active

## 2. Tiendas

In [12]:
# Dataframe inicial de tiendas
tiendas.head()

store_id     store_name   location          manager opening_date
0       501  Tienda Centro     Madrid       Juan Perez   2022-01-10
1       502   Tienda Norte  Barcelona      Laura Lopez   2022-02-05
2       503     Tienda Sur    Sevilla   Carlos Ramirez   2022-03-01
3       504    Tienda Este   Valencia        Ana Gomez   2022-04-15
4       505   Tienda Oeste     Bilbao  Pedro Hernandez   2022-05-01

In [13]:
# Verificamos si hay valores nulos
tiendas.isnull().sum()

store_id        0
store_name      0
location        0
manager         0
opening_date    0
dtype: int64

In [14]:
# Verificamos duplicados de tiendas por store_id ya que así podremos identificar si hay tiendas duplicadas
tiendas.duplicated(subset='store_id').sum()

1

In [15]:
# Eliminamos las tiendas duplicadas por store_id
tiendas.drop_duplicates(subset='store_id', inplace=True)


Formato de los datos

In [16]:
tiendas.dtypes

store_id         int64
store_name      object
location        object
manager         object
opening_date    object
dtype: object

In [17]:
# Transformamos los datos a su tipo correspondiente: opening_date a datetime
tiendas['opening_date'] = pd.to_datetime(tiendas['opening_date'])

In [18]:
# Reemplazamos el manager que no tiene nombre de la tienda Pop-up Store por Desconocido y aque antes solo tenía un guión
tiendas['manager'].replace({'-': 'Desconocido'}, inplace=True)

In [19]:
# Verificamos como queda la tabla de tiendas
tiendas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9 entries, 0 to 8
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype         
---  ------        --------------  -----         
 0   store_id      9 non-null      int64         
 1   store_name    9 non-null      object        
 2   location      9 non-null      object        
 3   manager       9 non-null      object        
 4   opening_date  9 non-null      datetime64[ns]
dtypes: datetime64[ns](1), int64(1), object(3)
memory usage: 432.0+ bytes


In [20]:
# Dataframe final de tiendas
tiendas.head()

store_id     store_name   location          manager opening_date
0       501  Tienda Centro     Madrid       Juan Perez   2022-01-10
1       502   Tienda Norte  Barcelona      Laura Lopez   2022-02-05
2       503     Tienda Sur    Sevilla   Carlos Ramirez   2022-03-01
3       504    Tienda Este   Valencia        Ana Gomez   2022-04-15
4       505   Tienda Oeste     Bilbao  Pedro Hernandez   2022-05-01

## 3. Ventas

In [21]:
# Dataframe inicial de ventas
ventas.head()

sale_id        date  store_id  product_id  units_sold  total_revenue  \
0    10001  2023-01-02       501         101           5            450   
1    10002  2023-01-03       501         102           3            180   
2    10003  2023-01-03       501         105           1             80   
3    10004  2023-01-15       502         103           2             60   
4    10005  2023-02-10       502         104           1             50   

  total_cost  
0        300  
1        120  
2        NaN  
3         40  
4         30

In [22]:
# Verificamos si hay valores nulos
ventas.isnull().sum()

sale_id          0
date             0
store_id         0
product_id       0
units_sold       0
total_revenue    0
total_cost       1
dtype: int64

In [23]:
# Reemplazamos los valores nulos de total_cost por el 30% menos del total_revenue ya quw por la tendencia de los datos se puede inferir que el costo es el 30% menos del precio
ventas['total_cost'].fillna(ventas['total_revenue'] - ventas['total_revenue'] * 0.3, inplace=True)

In [24]:
# Verificamos si hay duplicados en ventas
ventas.duplicated().sum()

0

Formato de los datos

In [25]:
ventas.dtypes


sale_id           int64
date             object
store_id          int64
product_id        int64
units_sold        int64
total_revenue     int64
total_cost       object
dtype: object

In [26]:
# Transformamos los datos a su tipo correspondiente: total_revenue a float, date a datetime
ventas['total_revenue'] = ventas['total_revenue'].astype(float)
ventas['date'] = pd.to_datetime(ventas['date'])

In [27]:
# Comprobamos espacios en blanco en ventas, para saber si hay datos que no se han registrado
(ventas == ' ').sum()

sale_id          0
date             0
store_id         0
product_id       0
units_sold       0
total_revenue    0
total_cost       2
dtype: int64

In [28]:
# Reemplazamos los espacios en blanco por valores nulos para modificarlos posteriormente con el método fillna
ventas['total_cost'].replace(' ', pd.NA, inplace=True)
ventas.isnull().sum() # Combprobamos que se hayan reemplazado los espacios en blanco

sale_id          0
date             0
store_id         0
product_id       0
units_sold       0
total_revenue    0
total_cost       2
dtype: int64

In [29]:
# Reemplazamos los valores nulos de total_cost por el 30% menos del total_revenue ya que por la tendencia de los datos se puede inferir que el costo es el 30% menos del precio
ventas['total_cost'].fillna(ventas['total_revenue'] - ventas['total_revenue'] * 0.3, inplace=True)

In [30]:
# Transformamos los datos a su tipo correspondiente: total_cost a float
ventas['total_cost'] = ventas['total_cost'].astype(float)

In [31]:
# Verificamos como queda la tabla de ventas
ventas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33 entries, 0 to 32
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype         
---  ------         --------------  -----         
 0   sale_id        33 non-null     int64         
 1   date           33 non-null     datetime64[ns]
 2   store_id       33 non-null     int64         
 3   product_id     33 non-null     int64         
 4   units_sold     33 non-null     int64         
 5   total_revenue  33 non-null     float64       
 6   total_cost     33 non-null     float64       
dtypes: datetime64[ns](1), float64(2), int64(4)
memory usage: 1.9 KB


In [32]:
# Dataframe final de ventas
ventas.head()

sale_id       date  store_id  product_id  units_sold  total_revenue  \
0    10001 2023-01-02       501         101           5          450.0   
1    10002 2023-01-03       501         102           3          180.0   
2    10003 2023-01-03       501         105           1           80.0   
3    10004 2023-01-15       502         103           2           60.0   
4    10005 2023-02-10       502         104           1           50.0   

   total_cost  
0       300.0  
1       120.0  
2        56.0  
3        40.0  
4        30.0

## 4. DataFrame-Final

In [33]:
# Unimos la tabla productos con ventas en base a product_id a través de un merge
productos_ventas = pd.merge(ventas, productos, on='product_id', how='left')
productos_ventas.head()

sale_id       date  store_id  product_id  units_sold  total_revenue  \
0    10001 2023-01-02       501         101           5          450.0   
1    10002 2023-01-03       501         102           3          180.0   
2    10003 2023-01-03       501         105           1           80.0   
3    10004 2023-01-15       502         103           2           60.0   
4    10005 2023-02-10       502         104           1           50.0   

   total_cost           product_name           category  price  cost  \
0       300.0       Cafetera Premium  Electrodomesticos   90.0  60.0   
1       120.0        Cafetera Básica  Electrodomesticos   60.0  40.0   
2        56.0      Batidora Compacta  Electrodomesticos   80.0  56.0   
3        40.0  Tostadora 2 rebanadas  Electrodomesticos   30.0  20.0   
4        30.0  Tostadora 4 rebanadas  Electrodomesticos   50.0  30.0   

  launch_date  status  
0  2023-01-01  active  
1  2023-01-15  active  
2  2023-02-01  active  
3  2022-11-01  active  
4  2022-12-01  paused

In [34]:
# Unimos el resultado de producto_ventas con tiendas en base a store_id a través de un merge para obtener el dataframe final
df_final = pd.merge(productos_ventas, tiendas, on='store_id', how='left')
df_final.head()

sale_id       date  store_id  product_id  units_sold  total_revenue  \
0    10001 2023-01-02       501         101           5          450.0   
1    10002 2023-01-03       501         102           3          180.0   
2    10003 2023-01-03       501         105           1           80.0   
3    10004 2023-01-15       502         103           2           60.0   
4    10005 2023-02-10       502         104           1           50.0   

   total_cost           product_name           category  price  cost  \
0       300.0       Cafetera Premium  Electrodomesticos   90.0  60.0   
1       120.0        Cafetera Básica  Electrodomesticos   60.0  40.0   
2        56.0      Batidora Compacta  Electrodomesticos   80.0  56.0   
3        40.0  Tostadora 2 rebanadas  Electrodomesticos   30.0  20.0   
4        30.0  Tostadora 4 rebanadas  Electrodomesticos   50.0  30.0   

  launch_date  status     store_name   location      manager opening_date  
0  2023-01-01  active  Tienda Centro     Madrid   Juan Perez   2022-01-10  
1  2023-01-15  active  Tienda Centro     Madrid   Juan Perez   2022-01-10  
2  2023-02-01  active  Tienda Centro     Madrid   Juan Perez   2022-01-10  
3  2022-11-01  active   Tienda Norte  Barcelona  Laura Lopez   2022-02-05  
4  2022-12-01  paused   Tienda Norte  Barcelona  Laura Lopez   2022-02-05

In [35]:
# Nombre de las columnas
df_final.columns

Index(['sale_id', 'date', 'store_id', 'product_id', 'units_sold',
       'total_revenue', 'total_cost', 'product_name', 'category', 'price',
       'cost', 'launch_date', 'status', 'store_name', 'location', 'manager',
       'opening_date'],
      dtype='object')

In [36]:
# Modificamos los nombres de las varriables para distinguir mejor los datos
df_final.rename(columns={'date': 'sale_date', 'price': 'product_price', 'cost': 'product_cost', 'status': 'product_status'}, inplace=True)

In [37]:
# Quitamos las tildes de las columnas de product_name y category para evitar problemas de búsqueda y comparación
# Función para eliminar tildes
def elimina_tildes_pandas(cadena):
    if isinstance(cadena, str):  # Verifica si es una cadena
        return ''.join(c for c in unicodedata.normalize('NFD', cadena) if unicodedata.category(c) != 'Mn')
    return cadena  # Devuelve el mismo valor si no es una cadena

columnas_a_modificar = ['product_name', 'category'] # Columnas a modificar
df_final[columnas_a_modificar] = df_final[columnas_a_modificar].applymap(elimina_tildes_pandas) # Aplicamos la función
df_final.head()

sale_id  sale_date  store_id  product_id  units_sold  total_revenue  \
0    10001 2023-01-02       501         101           5          450.0   
1    10002 2023-01-03       501         102           3          180.0   
2    10003 2023-01-03       501         105           1           80.0   
3    10004 2023-01-15       502         103           2           60.0   
4    10005 2023-02-10       502         104           1           50.0   

   total_cost           product_name           category  product_price  \
0       300.0       Cafetera Premium  Electrodomesticos           90.0   
1       120.0        Cafetera Basica  Electrodomesticos           60.0   
2        56.0      Batidora Compacta  Electrodomesticos           80.0   
3        40.0  Tostadora 2 rebanadas  Electrodomesticos           30.0   
4        30.0  Tostadora 4 rebanadas  Electrodomesticos           50.0   

   product_cost launch_date product_status     store_name   location  \
0          60.0  2023-01-01         active  Tienda Centro     Madrid   
1          40.0  2023-01-15         active  Tienda Centro     Madrid   
2          56.0  2023-02-01         active  Tienda Centro     Madrid   
3          20.0  2022-11-01         active   Tienda Norte  Barcelona   
4          30.0  2022-12-01         paused   Tienda Norte  Barcelona   

       manager opening_date  
0   Juan Perez   2022-01-10  
1   Juan Perez   2022-01-10  
2   Juan Perez   2022-01-10  
3  Laura Lopez   2022-02-05  
4  Laura Lopez   2022-02-05

In [38]:
# Comprobamos si hay valores nulos
df_final.isnull().sum()

sale_id           0
sale_date         0
store_id          0
product_id        0
units_sold        0
total_revenue     0
total_cost        0
product_name      3
category          3
product_price     3
product_cost      3
launch_date       3
product_status    3
store_name        1
location          1
manager           1
opening_date      1
dtype: int64

In [39]:
# comprobamos las filas con valores nulos 
df_final[df_final.isnull().any(axis=1)]

sale_id  sale_date  store_id  product_id  units_sold  total_revenue  \
14    10015 2023-03-20       501         999           1          200.0   
19    10020 2023-04-05       999         101           2          180.0   
28    10029 2023-04-20       504         999           5         1000.0   
32    10033 2023-05-03       508         999           1          200.0   

    total_cost      product_name           category  product_price  \
14       100.0               NaN                NaN            NaN   
19       120.0  Cafetera Premium  Electrodomesticos           90.0   
28       750.0               NaN                NaN            NaN   
32       150.0               NaN                NaN            NaN   

    product_cost launch_date product_status     store_name   location  \
14           NaN         NaT            NaN  Tienda Centro     Madrid   
19          60.0  2023-01-01         active            NaN        NaN   
28           NaN         NaT            NaN    Tienda Este   Valencia   
32           NaN         NaT            NaN   Pop-up Store  Barcelona   

        manager opening_date  
14   Juan Perez   2022-01-10  
19          NaN          NaT  
28    Ana Gomez   2022-04-15  
32  Desconocido   2023-01-01

El product_id 999 no tiene registros de producto asociado por lo que procedemos a comprobarlo si se encuentra en la tabla de productos.
Así también, el prodcut_id 101 no tiene registros de tienda , realizamos lo mismo con la tabla de tiendas.

In [40]:
# Fitramos los product_id de ventas que no estén en la tabla de productos para asegurarnos que el producto no esté registrado en la tabla de productos
coincidencias = ventas[~ventas['product_id'].isin(productos['product_id'])]
product_ids_no_en_productos = coincidencias['product_id'].unique() # Obtenemos los product_id que no están en productos
print('Product_id en ventas pero no en productos:', product_ids_no_en_productos) 
print('Número de registros con product_id 999 en ventas y no en productos:', coincidencias.shape[0])

Product_id en ventas pero no en productos: [999]
Número de registros con product_id 999 en ventas y no en productos: 3


In [41]:
# Fitramos los store_id de ventas que no estén en la tabla de tiendas para asegurarnos que la tienda no esté registrada en la tabla de tiendas
coincidencia_tiendas = ventas[~ventas['store_id'].isin(tiendas['store_id'])]
store_ids_no_en_tiendas = coincidencia_tiendas['store_id'].unique() # Obtenemos los store_id que no están en tiendas
print('Store_id en ventas pero no en tiendas:', store_ids_no_en_tiendas)
print('Número de registros con store_id 999 en ventas y no en tiendas:', coincidencia_tiendas.shape[0])

Store_id en ventas pero no en tiendas: [999]
Número de registros con store_id 999 en ventas y no en tiendas: 1


Reemplazamos valores nulos en df_final


- Product_id 999

In [42]:
# Reemplazamos los valores nulos de product_id 999
# Product_price y product_cost se reemplazan por el promedio de total_revenue y total_cost respectivamente
df_final['product_price'].fillna(df_final['total_revenue']/ df_final['units_sold'], inplace=True)
df_final['product_cost'].fillna(df_final['total_cost']/ df_final['units_sold'], inplace=True)

In [43]:
# Filtrar por ubicación en Madrid, Valencia y Barcelona que es donde se vende el product_id 999 para conocer las ventas por categoría
ciudades = ['Madrid', 'Valencia', 'Barcelona']
df_final[df_final['location'].isin(ciudades)].groupby('category')['units_sold'].sum().sort_values(ascending=False)

category
Electrodomesticos    33
Hogar                 6
Electronica           3
Name: units_sold, dtype: int64

In [44]:
# Los Productos que más se venden en Madrid, Valencia y Barcelona son los electrodomésticos
df_final['category'].fillna('Electrodomésticos', inplace=True) # Reemplazamos los valores nulos de category por Electrodomésticos

In [45]:
# Estatus y launched_date se reemplazan por el valor más común y la fecha más común
df_final['product_status'].fillna(df_final['product_status'].mode()[0], inplace=True)
df_final['launch_date'].fillna(df_final['launch_date'].mode()[0], inplace=True)

In [46]:
# Product_name se reemplaza por desconocido ya que no se tiene información y es más complicado de interpretar
df_final['product_name'].fillna('Desconocido', inplace=True)

In [47]:
# Comprobamos como quedan los valores reemplazados
df_final[df_final['product_id'] == 999]

sale_id  sale_date  store_id  product_id  units_sold  total_revenue  \
14    10015 2023-03-20       501         999           1          200.0   
28    10029 2023-04-20       504         999           5         1000.0   
32    10033 2023-05-03       508         999           1          200.0   

    total_cost product_name           category  product_price  product_cost  \
14       100.0  Desconocido  Electrodomésticos          200.0         100.0   
28       750.0  Desconocido  Electrodomésticos          200.0         150.0   
32       150.0  Desconocido  Electrodomésticos          200.0         150.0   

   launch_date product_status     store_name   location      manager  \
14  2023-01-01         active  Tienda Centro     Madrid   Juan Perez   
28  2023-01-01         active    Tienda Este   Valencia    Ana Gomez   
32  2023-01-01         active   Pop-up Store  Barcelona  Desconocido   

   opening_date  
14   2022-01-10  
28   2022-04-15  
32   2023-01-01

- Product_id 101 con store_id 999. 
  Este caso es complejo, ya que especificar los datos de la tienda requiere de mayor dificultad antes las posibles opciones.

In [48]:
# Product_id 101 fue vendido por la tienda_id store 999
df_final[df_final['product_id']== 101]

sale_id  sale_date  store_id  product_id  units_sold  total_revenue  \
0     10001 2023-01-02       501         101           5          450.0   
12    10013 2023-03-10       507         101          10          850.0   
19    10020 2023-04-05       999         101           2          180.0   
31    10032 2023-05-02       508         101           4          360.0   

    total_cost      product_name           category  product_price  \
0        300.0  Cafetera Premium  Electrodomesticos           90.0   
12       600.0  Cafetera Premium  Electrodomesticos           90.0   
19       120.0  Cafetera Premium  Electrodomesticos           90.0   
31       240.0  Cafetera Premium  Electrodomesticos           90.0   

    product_cost launch_date product_status     store_name    location  \
0           60.0  2023-01-01         active  Tienda Centro      Madrid   
12          60.0  2023-01-01         active   Tienda Móvil  Itinerante   
19          60.0  2023-01-01         active            NaN         NaN   
31          60.0  2023-01-01         active   Pop-up Store   Barcelona   

        manager opening_date  
0    Juan Perez   2022-01-10  
12   Maria Diaz   2022-06-10  
19          NaN          NaT  
31  Desconocido   2023-01-01

In [49]:
# Reemplazamos los valores nulos de store_id 999 por desconocido menos opening_date que se reemplaza por la fecha más común
df_final[['store_name', 'location', 'manager']] = df_final[['store_name', 'location', 'manager']].fillna('Desconocido')
df_final['opening_date'].fillna(df_final['opening_date'].mode()[0], inplace=True)

- Ordenamos de forma estructurada las columnas para primero identificar la venta, luego la tienda relacionada con esa venta, después la información del producto y finalmente los detalles económicos relacionados con la venta.

In [54]:
# Nuevo orden de las columnas
df_final = df_final[[
    'sale_id', 'sale_date', 
    'store_id', 'store_name', 'location', 'manager', 'opening_date',
    'product_id', 'product_name', 'category', 'product_price', 'product_cost', 'launch_date', 'product_status',
    'units_sold', 'total_cost', 'total_revenue'
]]


### - **DataFrame Final**

In [55]:
# Guardamos el dataframe final en un archivo csv
df_final.to_csv('..\\data\\df_final.csv', index=False)
df_final

sale_id  sale_date  store_id        store_name     location  \
0     10001 2023-01-02       501     Tienda Centro       Madrid   
1     10002 2023-01-03       501     Tienda Centro       Madrid   
2     10003 2023-01-03       501     Tienda Centro       Madrid   
3     10004 2023-01-15       502      Tienda Norte    Barcelona   
4     10005 2023-02-10       502      Tienda Norte    Barcelona   
5     10006 2023-02-11       502      Tienda Norte    Barcelona   
6     10007 2023-02-15       503        Tienda Sur      Sevilla   
7     10008 2023-02-16       503        Tienda Sur      Sevilla   
8     10009 2023-02-20       504       Tienda Este     Valencia   
9     10010 2023-03-01       501     Tienda Centro       Madrid   
10    10011 2023-03-05       506  Tienda Duplicada       Madrid   
11    10012 2023-03-05       506  Tienda Duplicada       Madrid   
12    10013 2023-03-10       507      Tienda Móvil   Itinerante   
13    10014 2023-03-11       507      Tienda Móvil   Itinerante   
14    10015 2023-03-20       501     Tienda Centro       Madrid   
15    10016 2023-03-25       509     Tienda Online       Online   
16    10017 2023-03-26       509     Tienda Online       Online   
17    10018 2023-04-01       501     Tienda Centro       Madrid   
18    10019 2023-04-02       501     Tienda Centro       Madrid   
19    10020 2023-04-05       999       Desconocido  Desconocido   
20    10021 2023-04-06       502      Tienda Norte    Barcelona   
21    10022 2023-04-07       502      Tienda Norte    Barcelona   
22    10023 2023-04-07       502      Tienda Norte    Barcelona   
23    10024 2023-04-10       505      Tienda Oeste       Bilbao   
24    10025 2023-04-10       505      Tienda Oeste       Bilbao   
25    10026 2023-04-11       505      Tienda Oeste       Bilbao   
26    10027 2023-04-15       509     Tienda Online       Online   
27    10028 2023-04-16       504       Tienda Este     Valencia   
28    10029 2023-04-20       504       Tienda Este     Valencia   
29    10030 2023-05-01       506  Tienda Duplicada       Madrid   
30    10031 2023-05-02       506  Tienda Duplicada       Madrid   
31    10032 2023-05-02       508      Pop-up Store    Barcelona   
32    10033 2023-05-03       508      Pop-up Store    Barcelona   

            manager opening_date  product_id           product_name  \
0        Juan Perez   2022-01-10         101       Cafetera Premium   
1        Juan Perez   2022-01-10         102        Cafetera Basica   
2        Juan Perez   2022-01-10         105      Batidora Compacta   
3       Laura Lopez   2022-02-05         103  Tostadora 2 rebanadas   
4       Laura Lopez   2022-02-05         104  Tostadora 4 rebanadas   
5       Laura Lopez   2022-02-05         106           Lavadora 7kg   
6    Carlos Ramirez   2022-03-01         107     Tableta 8 pulgadas   
7    Carlos Ramirez   2022-03-01         108  Smartphone Gama Media   
8         Ana Gomez   2022-04-15         109   Smartphone Gama Alta   
9        Juan Perez   2022-01-10         110          Laptop Basica   
10     Julian Casas   2022-05-20         105      Batidora Compacta   
11     Julian Casas   2022-05-20         117      Pack Cuchillos x3   
12       Maria Diaz   2022-06-10         101       Cafetera Premium   
13       Maria Diaz   2022-06-10         120        Plancha de Ropa   
14       Juan Perez   2022-01-10         999            Desconocido   
15  Virtual Manager   2022-07-01         115               Termo 1L   
16  Virtual Manager   2022-07-01         114            Termo 500ml   
17       Juan Perez   2022-01-10         116       Aspiradora Robot   
18       Juan Perez   2022-01-10         117      Pack Cuchillos x3   
19      Desconocido   2022-01-10         101       Cafetera Premium   
20      Laura Lopez   2022-02-05         119      Ventilador de Pie   
21      Laura Lopez   2022-02-05         120        Plancha de Ropa   
22      Laura Lopez   2022-02-05         120        Plancha de Ropa   
23  Pedro Hernandez  